name: MoreFeatures
version: 1.0.0
main: net.gravijet.morefeatures.Main
author: gravijet
description: More features for example.invalid
depend: [NoteBlockAPI]

commands:
  bridgesync:
    description: Forces an immediate Bridge sync
    permission: bridge.sync
    usage: /bridgesync
  music:
    description: Main music control hub
    aliases: [m]
    permission: morefeatures.music.play
    usage: /music <play|stop|force|list|download|info>
  rickroll:
    description: Rickroll yourself or another player
    permission: morefeatures.rickroll
    usage: /rickroll [player] <time>

permissions:
  bridge.sync:
    description: Allows running /bridgesync
    default: op
  morefeatures.music.play:
    description: Play music for yourself
    default: true
  morefeatures.music.stop:
    description: Stop your own music
    default: true
  morefeatures.music.list:
    description: List available songs
    default: true
  morefeatures.music.info:
    description: Show currently playing song info
    default: true
  morefeatures.music.volume:
    description: Change default playback volume
    default: true
  morefeatures.music.force:
    description: Force play music for other players
    default: op
  morefeatures.music.download:
    description: Manually trigger song download
    default: op
  morefeatures.rickroll:
    description: Rickroll yourself
    default: true
  morefeatures.rickroll.others:
    description: Rickroll other players
    default: op
